---
- name: Deploy Monitoring Stack
  hosts: localhost
  connection: local

  tasks:
    - name: Start monitoring stack
      command: docker compose up -d
      args:
        chdir: /home/lenovo/linux-sre-automation-stack/monitoring

    - name: Show running containers
      command: docker ps
      register: docker_ps

    - name: Display running containers
      debug:
        var: docker_ps.stdout_lines
